#!/usr/bin/env python3
from io import BytesIO
from pathlib import Path
from urllib.request import urlopen

import cairosvg
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "components/ui/ui_remote_icons.c"
BASE = "https://raw.githubusercontent.com/Remix-Design/RemixIcon/master/icons"
SIZE = 32

ICONS = [
    ("power", "Device/shut-down-line.svg", "UI_REMOTE_ICON_POWER"),
    ("input", "Device/remote-control-line.svg", "UI_REMOTE_ICON_INPUT"),
    ("home", "Buildings/home-5-line.svg", "UI_REMOTE_ICON_HOME"),
    ("back", "Arrows/arrow-go-back-line.svg", "UI_REMOTE_ICON_BACK"),
    ("settings", "System/settings-3-line.svg", "UI_REMOTE_ICON_SETTINGS"),
    ("display", "Device/tv-2-line.svg", "UI_REMOTE_ICON_DISPLAY"),
    ("add", "System/add-line.svg", "UI_REMOTE_ICON_ADD"),
    ("subtract", "System/subtract-line.svg", "UI_REMOTE_ICON_SUBTRACT"),
]


def fetch_alpha(rel_path: str) -> bytes:
    with urlopen(f"{BASE}/{rel_path}", timeout=30) as response:
        svg = response.read()
    png = cairosvg.svg2png(bytestring=svg, output_width=SIZE, output_height=SIZE)
    image = Image.open(BytesIO(png)).convert("RGBA")
    return bytes(image.getchannel("A").getdata())


def c_bytes(data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append("    " + ",".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


parts = [
    '#include "ui_remote_icons.h"',
    '',
    '#include <stddef.h>',
    '',
    '/*',
    ' * AUTO-GENERATED by tools/generate_remote_icons.py.',
    ' * Official Remix Icon SVG geometry rasterized directly to antialiased LVGL A8.',
    ' * All remote-control icons are 32x32.',
    ' */',
]

mapping = []
for name, rel_path, enum_name in ICONS:
    data = fetch_alpha(rel_path)
    parts.extend([
        f'/* Remix Icon: {rel_path} */',
        f'static const uint8_t {name}_buf[{len(data)}] = {{',
        c_bytes(data),
        '};',
        f'static const lv_image_dsc_t {name}_img = {{',
        f'    .header = {{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,.w={SIZE},.h={SIZE},.stride={SIZE},.reserved_2=0}},',
        f'    .data_size = sizeof({name}_buf),',
        f'    .data = {name}_buf,',
        '    .reserved = NULL,',
        '};',
        '',
    ])
    mapping.append((enum_name, name))

parts.extend([
    'static const lv_image_dsc_t *descriptor_for(ui_remote_icon_t type)',
    '{',
    '    switch(type) {',
])
for enum_name, name in mapping:
    parts.append(f'        case {enum_name}: return &{name}_img;')
parts.extend([
    '        default: return &power_img;',
    '    }',
    '}',
    '',
    'lv_obj_t *ui_remote_icon_create(lv_obj_t *parent, ui_remote_icon_t icon, lv_color_t color)',
    '{',
    '    lv_obj_t *image = lv_image_create(parent);',
    '    lv_image_set_src(image, descriptor_for(icon));',
    '    lv_obj_set_style_image_recolor(image, color, 0);',
    '    lv_obj_set_style_image_recolor_opa(image, LV_OPA_COVER, 0);',
    '    lv_obj_clear_flag(image, LV_OBJ_FLAG_CLICKABLE);',
    '    lv_obj_clear_flag(image, LV_OBJ_FLAG_SCROLLABLE);',
    '    return image;',
    '}',
    '',
])

OUT.write_text("\n".join(parts), encoding="utf-8")
print(f"Generated: {OUT}")
