#!/usr/bin/env python3
from io import BytesIO
from pathlib import Path
from urllib.request import urlopen

import cairosvg
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "components/ui/ui_lights_icons.c"
BASE = "https://raw.githubusercontent.com/Remix-Design/RemixIcon/master/icons"

ICONS = [
    ("sofa", "Others/sofa-line.svg", 40, "UI_LIGHTS_ICON_SOFA"),
    ("computer", "Device/computer-line.svg", 40, "UI_LIGHTS_ICON_COMPUTER"),
    ("bed", "Map/hotel-bed-line.svg", 40, "UI_LIGHTS_ICON_BED"),
    ("bulb", "Others/lightbulb-line.svg", 40, "UI_LIGHTS_ICON_BULB"),
    ("tv", "Device/tv-line.svg", 40, "UI_LIGHTS_ICON_TV"),
    ("drop", "Design/drop-line.svg", 40, "UI_LIGHTS_ICON_DROP"),
    ("window", "Business/window-line.svg", 40, "UI_LIGHTS_ICON_WINDOW"),
    ("sun", "Weather/sun-line.svg", 24, "UI_LIGHTS_ICON_BRIGHTNESS"),
    ("temp", "Weather/temp-hot-line.svg", 24, "UI_LIGHTS_ICON_TEMPERATURE"),
    ("palette", "Design/palette-line.svg", 24, "UI_LIGHTS_ICON_PALETTE"),
]


def fetch_alpha(rel_path: str, size: int) -> bytes:
    with urlopen(f"{BASE}/{rel_path}", timeout=30) as response:
        svg = response.read()
    png = cairosvg.svg2png(bytestring=svg, output_width=size, output_height=size)
    image = Image.open(BytesIO(png)).convert("RGBA")
    return bytes(image.getchannel("A").getdata())


def c_bytes(data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append("    " + ",".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


parts = [
    '#include "ui_lights_icons.h"',
    '',
    '#include <stddef.h>',
    '',
    '/*',
    ' * AUTO-GENERATED by tools/generate_lights_icons.py.',
    ' * Official Remix Icon SVG geometry rasterized directly to antialiased LVGL A8.',
    ' * Room icons are 40x40; footer control icons are 24x24.',
    ' */',
]

mapping = []
for name, rel_path, size, enum_name in ICONS:
    data = fetch_alpha(rel_path, size)
    parts.extend([
        f'/* Remix Icon: {rel_path} */',
        f'static const uint8_t {name}_buf[{len(data)}] = {{',
        c_bytes(data),
        '};',
        f'static const lv_image_dsc_t {name}_img = {{',
        f'    .header = {{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,.w={size},.h={size},.stride={size},.reserved_2=0}},',
        f'    .data_size = sizeof({name}_buf),',
        f'    .data = {name}_buf,',
        '    .reserved = NULL,',
        '};',
        '',
    ])
    mapping.append((enum_name, name))

parts.extend([
    'static const lv_image_dsc_t *descriptor_for(ui_lights_icon_t type)',
    '{',
    '    switch(type) {',
])
for enum_name, name in mapping:
    parts.append(f'        case {enum_name}: return &{name}_img;')
parts.extend([
    '        default: return &bulb_img;',
    '    }',
    '}',
    '',
    'lv_obj_t *ui_lights_icon_create(lv_obj_t *parent, ui_lights_icon_t type, lv_color_t color)',
    '{',
    '    lv_obj_t *icon = lv_image_create(parent);',
    '    lv_image_set_src(icon, descriptor_for(type));',
    '    lv_obj_set_style_image_recolor(icon, color, 0);',
    '    lv_obj_set_style_image_recolor_opa(icon, LV_OPA_COVER, 0);',
    '    lv_obj_clear_flag(icon, LV_OBJ_FLAG_CLICKABLE);',
    '    lv_obj_clear_flag(icon, LV_OBJ_FLAG_SCROLLABLE);',
    '    return icon;',
    '}',
    '',
    'void ui_lights_icon_set_color(lv_obj_t *icon, lv_color_t color)',
    '{',
    '    if(!icon) return;',
    '    lv_obj_set_style_image_recolor(icon, color, 0);',
    '    lv_obj_set_style_image_recolor_opa(icon, LV_OPA_COVER, 0);',
    '}',
    '',
])

OUT.write_text("\n".join(parts), encoding="utf-8")
print(f"Generated: {OUT}")
