#!/usr/bin/env python3
from pathlib import Path
from urllib.request import urlopen
import io

import cairosvg
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "components/ui/ui_asset_timer.c"

ICON_URL = "https://raw.githubusercontent.com/Remix-Design/RemixIcon/master/icons/System/timer-line.svg"
FONT_URL = "https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/OTF/SimplifiedChinese/SourceHanSansSC-Normal.otf"

ICON_W = 58
ICON_H = 58
LABEL_W = 66
LABEL_H = 24
LABEL_TEXT = "计时器"
LABEL_SIZE = 22
SUPERSAMPLE = 4


def fetch(url: str) -> bytes:
    with urlopen(url, timeout=60) as response:
        return response.read()


def rle(data):
    data = list(data)
    if not data:
        return []
    out = []
    value = int(data[0])
    count = 1
    for item in data[1:]:
        item = int(item)
        if item == value and count < 255:
            count += 1
        else:
            out.extend((count, value))
            value = item
            count = 1
    out.extend((count, value))
    return out


def c_array(data, width=24):
    lines = []
    for i in range(0, len(data), width):
        lines.append("    " + ",".join(f"0x{x:02x}" for x in data[i:i + width]) + ",")
    return "\n".join(lines)


def render_icon(svg_bytes: bytes):
    # Render large and downsample once so diagonal/circular edges retain A8 anti-aliasing.
    png = cairosvg.svg2png(
        bytestring=svg_bytes,
        output_width=ICON_W * SUPERSAMPLE,
        output_height=ICON_H * SUPERSAMPLE,
    )
    image = Image.open(io.BytesIO(png)).convert("RGBA")
    alpha = image.getchannel("A")
    return alpha.resize((ICON_W, ICON_H), Image.Resampling.LANCZOS)


def render_label(font_bytes: bytes):
    font_file = io.BytesIO(font_bytes)
    font = ImageFont.truetype(font_file, LABEL_SIZE * SUPERSAMPLE)
    image = Image.new("L", (LABEL_W * SUPERSAMPLE, LABEL_H * SUPERSAMPLE), 0)
    draw = ImageDraw.Draw(image)
    box = draw.textbbox((0, 0), LABEL_TEXT, font=font)
    x = (image.width - (box[2] - box[0])) // 2 - box[0]
    y = (image.height - (box[3] - box[1])) // 2 - box[1]
    draw.text((x, y), LABEL_TEXT, font=font, fill=255)
    return image.resize((LABEL_W, LABEL_H), Image.Resampling.LANCZOS)


def main():
    icon = render_icon(fetch(ICON_URL))
    label = render_label(fetch(FONT_URL))
    icon_rle = rle(np.asarray(icon, dtype=np.uint8).reshape(-1))
    label_rle = rle(np.asarray(label, dtype=np.uint8).reshape(-1))

    source = f'''#include "ui_assets.h"\n#include <stddef.h>\n\n/*\n * Generated by tools/generate_timer_asset.py.\n * Icon: Remix Icon System/timer-line.svg.\n * Label: Source Han Sans SC Normal, 22 px visual size.\n * Both are stored as anti-aliased A8 masks to match the HOME asset pipeline.\n */\nstatic void decode_rle(const uint8_t *src, size_t src_len, uint8_t *dst, size_t dst_len)\n{{\n    size_t si = 0, di = 0;\n    while (si + 1 < src_len && di < dst_len) {{\n        uint8_t count = src[si++];\n        uint8_t value = src[si++];\n        while (count-- && di < dst_len) dst[di++] = value;\n    }}\n}}\n\nstatic const uint8_t ui_icon_timer_rle[] = {{\n{c_array(icon_rle)}\n}};\nstatic uint8_t ui_icon_timer_buf[{ICON_W * ICON_H}];\nlv_image_dsc_t ui_icon_timer = {{\n    .header = {{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,.w={ICON_W},.h={ICON_H},.stride={ICON_W},.reserved_2=0}},\n    .data_size = sizeof(ui_icon_timer_buf), .data = ui_icon_timer_buf, .reserved = NULL,\n}};\n\nstatic const uint8_t ui_label_timer_rle[] = {{\n{c_array(label_rle)}\n}};\nstatic uint8_t ui_label_timer_buf[{LABEL_W * LABEL_H}];\nlv_image_dsc_t ui_label_timer = {{\n    .header = {{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_A8,.flags=0,.w={LABEL_W},.h={LABEL_H},.stride={LABEL_W},.reserved_2=0}},\n    .data_size = sizeof(ui_label_timer_buf), .data = ui_label_timer_buf, .reserved = NULL,\n}};\n\nvoid ui_asset_timer_init(void)\n{{\n    decode_rle(ui_icon_timer_rle, sizeof(ui_icon_timer_rle), ui_icon_timer_buf, sizeof(ui_icon_timer_buf));\n    decode_rle(ui_label_timer_rle, sizeof(ui_label_timer_rle), ui_label_timer_buf, sizeof(ui_label_timer_buf));\n}}\n'''
    OUT.write_text(source, encoding="utf-8")
    print(f"Generated: {OUT}")


if __name__ == "__main__":
    main()
