name: Hello Robot TFLM inference build
on:
  push:
    paths:
      - "test_apps/hello_robot/**"
      - "models/wakeword/hello_robot_v1/**"
      - ".github/workflows/hello-robot-inference-build.yml"
  pull_request:
    paths:
      - "test_apps/hello_robot/**"
      - "models/wakeword/hello_robot_v1/**"
      - ".github/workflows/hello-robot-inference-build.yml"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.4
          target: esp32s3
          path: test_apps/hello_robot
          command: idf.py build
